---
- yum: name=http://yum.puppetlabs.com/puppetlabs-release-el-7.noarch.rpm state=present
- yum: name=git state=present
  when: development
- git: repo=https://github.com/stackforge/packstack
       dest=/opt/packstack
  when: development
- file: path=/opt/packstack owner=vagrant group=vagrant recurse=yes
  when: development
- command: python setup.py install
           chdir=/opt/packstack
  when: development
- command: python setup.py install_puppet_modules
           chdir=/opt/packstack
  when: development
- yum: name=openstack-packstack state=present
  when: not development
- template: src=files/openrc.j2 dest=/home/vagrant/openrc owner=vagrant group=vagrant mode=0644
- lineinfile: dest=/home/vagrant/.bashrc line='source $HOME/openrc'
- copy: src=files/scripts/ dest=/home/vagrant/scripts/ owner=vagrant group=vagrant mode=0755
- template: src=files/packstack.answers.j2 dest=/home/vagrant/packstack.answers owner=vagrant group=vagrant
- copy: src=files/gitconfig dest=/home/vagrant/.gitconfig owner=vagrant group=vagrant mode=0644
- file: src=/home/vagrant/.ssh/id_packstack dest=/home/vagrant/.ssh/id_rsa owner=vagrant group=vagrant state=link
- file: src=/home/vagrant/.ssh/id_packstack.pub dest=/home/vagrant/.ssh/id_rsa.pub owner=vagrant group=vagrant state=link
